Remove new_hostname from ping.c
Cacti/spine pull request #214
Opened 2021-07-07 20:46 UTC by eriksejr

This is an attempt to fix #211 and #209 which are probably duplicates. I believe the crash is due to a reversed strcpy() in ping_icmp, ping_udp and ping_tcp but the actual variable that is being copied does not seem necessary at all

2021-07-08 23:20 UTC, eriksejr commented
Also #217

2021-09-02 01:42 UTC, netniV requested changes
Yes, this makes more sense. I didn't go far enough when I removed the older tcp_udp parsing functon. Can you add a CHANGELOG entry for the change too?

2021-09-02 20:39 UTC, netniV commented
I have used a modified form of your code (fixes compiler warnings) but essentially your fix was the best of three attempts from people 👍

2021-09-02 20:39 UTC, closed without merging

2021-09-02 20:45 UTC, eriksejr commented
Ah ok no problem. I'll get to the CHANGELOG for the other fix tomorrow. Sorry I wanted to get to this today but I just ran out of time.

2021-09-02 21:46 UTC, netniV commented
What was the other fix?  That may not be necessary now

2021-09-02 22:39 UTC, eriksejr commented
Just referring to PR#216 to get the CHANGELOG updated. I also might adjust that SQL query slightly as I don't think both the inner and outer IF's are required.